import { setRequestLocale } from 'next-intl/server'
import type { Metadata } from 'next'
import SectionWrapper from '@/components/shared/SectionWrapper'
import { BUSINESS_INFO, SITE_URL } from '@/lib/constants'
import { getBreadcrumbJsonLd } from '@/lib/jsonld'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'LENGOLF Privacy Policy - Learn about how we collect, use and protect your personal data.',
  alternates: { canonical: `${SITE_URL}/privacy-policy/` },
}

export default async function PrivacyPolicyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params
  setRequestLocale(locale)
  const breadcrumbJsonLd = getBreadcrumbJsonLd([
    { name: 'Home', url: `${SITE_URL}/` },
    { name: 'Privacy Policy', url: `${SITE_URL}/privacy-policy/` },
  ])

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
    <SectionWrapper>
      <div className="mx-auto max-w-3xl prose prose-headings:text-foreground prose-p:text-muted-foreground prose-li:text-muted-foreground prose-strong:text-foreground">
        <h1>Privacy Policy</h1>
        <p>Last updated: 7 August 2026</p>
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to {BUSINESS_INFO.legalName}, {BUSINESS_INFO.registeredAddress}.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Thailand</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          <li><strong>Website</strong> refers to LENGOLF, accessible from len.golf</li>
          <li><strong>You</strong> means the individual accessing or using the Service.</li>
        </ul>

        <h2>Collecting and Using Your Personal Data</h2>
        <h3>Types of Data Collected</h3>
        <h4>Personal Data</h4>
        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>

        <h4>Usage Data</h4>
        <p>
          Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>

        <h4>Tracking Technologies and Cookies</h4>
        <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The third-party tools we currently use are:</p>
        <ul>
          <li><strong>Google Tag Manager</strong> - loads and manages the tools below.</li>
          <li><strong>Google Analytics 4</strong> - how visitors find and use the Website, in aggregate.</li>
          <li><strong>Google Ads</strong> - measuring which advertising leads to a booking.</li>
          <li><strong>Meta (Facebook) Pixel</strong> - measuring the results of our Facebook and Instagram advertising.</li>
          <li><strong>Microsoft Clarity</strong> - anonymous analysis of how pages are used, to help us improve them.</li>
        </ul>
        <p>
          You can block or delete Cookies through Your browser settings. Blocking them does not stop You from booking
          with Us, but parts of the Website may work less well.
        </p>
        <h4>Payment Data</h4>
        <p>
          When You pay online, Your card details are entered into and processed by our payment provider. LENGOLF does
          not receive or store Your full card number. We retain only the record of the payment, such as the amount,
          the date, the result, the card brand, and the last four digits.
        </p>

        <h3>Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
          <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service.</li>
          <li><strong>For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract.</li>
          <li><strong>To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
          <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events.</li>
          <li><strong>To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
        </ul>

        <h3>Retention of Your Personal Data</h3>
        <p>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
          Privacy Policy. In practice that means:
        </p>
        <ul>
          <li>
            <strong>Booking and payment records</strong> - retained for at least 5 years, as required of Us by Thai
            accounting and tax law.
          </li>
          <li>
            <strong>Contact details and booking history</strong> - retained while You remain a customer, so that We can
            service Your bookings and honour any packages You hold.
          </li>
          <li>
            <strong>Marketing consent</strong> - retained until You withdraw it, together with a record of when and how
            it was given, so that We can show We had Your permission.
          </li>
          <li>
            <strong>Website analytics</strong> - retained according to the settings of the tools listed above,
            generally no more than 14 months.
          </li>
        </ul>
        <p>When Personal Data is no longer needed, We delete it or irreversibly anonymise it.</p>

        <h3>Security of Your Personal Data</h3>
        <p>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.
        </p>

        <h2>Your Rights Over Your Personal Data</h2>
        <p>
          Under Thailand&apos;s Personal Data Protection Act B.E. 2562 (2019) (&quot;PDPA&quot;), You have the
          following rights in relation to the Personal Data We hold about You:
        </p>
        <ul>
          <li><strong>Access</strong> - to ask for a copy of the Personal Data We hold about You.</li>
          <li><strong>Rectification</strong> - to have inaccurate or incomplete data corrected.</li>
          <li><strong>Erasure</strong> - to ask Us to delete or anonymise Your data, where We have no continuing legal reason to keep it.</li>
          <li><strong>Restriction</strong> - to ask Us to pause Our use of Your data while a request or objection is being resolved.</li>
          <li><strong>Objection</strong> - to object to Our use of Your data, including for direct marketing.</li>
          <li><strong>Data portability</strong> - to receive the data You gave Us in a commonly used machine-readable format, or to have it sent to another provider.</li>
          <li><strong>Withdrawal of consent</strong> - to withdraw consent at any time, where We rely on Your consent. Withdrawing consent does not affect anything We did lawfully before You withdrew it.</li>
          <li><strong>Complaint</strong> - to lodge a complaint with the Personal Data Protection Committee (PDPC) if You believe We have handled Your data unlawfully.</li>
        </ul>
        <p>
          To exercise any of these rights, contact Us using the details in the &quot;Contact Us&quot; section below. We
          will respond within the time required by the PDPA. We may need to verify Your identity before acting on a
          request, so that We do not disclose Your data to someone else. Exercising these rights is free of charge.
        </p>
        <p>
          You can unsubscribe from marketing messages at any time using the link in any marketing email We send You,
          or by contacting Us. This does not stop Us from sending You service messages about a booking You have made,
          such as a confirmation or a change of time.
        </p>

        <h2>Children&apos;s Privacy</h2>
        <p>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
        </p>

        <h2>Changes to this Privacy Policy</h2>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>

        <h2>Contact Us</h2>
        <p>
          {BUSINESS_INFO.legalName} is the data controller for the Personal Data described in this Privacy Policy. If
          You have any questions about this Privacy Policy, or wish to exercise any of the rights set out above, You
          can contact Us:
        </p>
        <ul>
          <li>By email: {BUSINESS_INFO.email}</li>
          <li>By phone: {BUSINESS_INFO.phone}</li>
          <li>By post: {BUSINESS_INFO.legalName}, {BUSINESS_INFO.registeredAddress}</li>
        </ul>
      </div>
    </SectionWrapper>
    </>
  )
}
